apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
namePrefix: dev-
nameSuffix: "-001"
images:
- name: petclinic
  newName: registry.cn-hangzhou.aliyuncs.com/laocai/spring-petclinic
  newTag: latest
